---
- name: Install Nginx
  gather_facts: No
  hosts: 127.0.0.1
  connection: local

- name: Install Nginx
    yum:
      name:
        - nginx
      state: present
      
- name: Replace nginx.conf
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf

- service:
      name: nginx
      state: started
      enabled: yes
