---
- name: Install Nginx
    yum:
      name:
        - nginx
      state: present
      
- name: Replace nginx.conf
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf

- service:
      name: nginx
      state: started
      enabled: yes
