---
- name: Install Nginx
  gather_facts: No
  hosts: 127.0.0.1
  connection: local

- name: Install Nginx
    yum:
      name:
        - nginx
      state: present

- service:
      name: nginx
      state: started
      enabled: yes
