---
- name: Install Python-APP
  gather_facts: No
  hosts: All
 
  tasks:
  
    - name: Copying .nginx
      copy:
        src: nginx.conf
        dest: /etc/nginx
        follow: yes

    - name: restart nginx
        systemd: name=nginx state=restarted enabled=yes
    
    - name: Install ius repo
      yum_repository:
        name: "ius"
        description: "ius yum repository"
        baseurl: "https://centos7.iuscommunity.org/ius-release.rpm"
    
    - name: Install PostgreSQL
      yum:
        name:
          - postgresql
          - postgresql-contrib
          - postgresql-server-dev-10
          - python-psycopg2
        state: present
    
    - name: Create test database
      postgresql_db:
        name: test    
    
    - name Create a PostgreSQL database user
      postgresql_user:
        db: test
        name=test_user
        password=DMg00LhU
        priv: "CONNECT/products:ALL"
        expires: infinity 
      
    - name: Install Python 3.6
      yum:
        name:
          - python36u
          - python36u-devel
          - python36u-pip
          - libpq-dev
          - gcc
        state: present    

    - name: clone repo
      git:
        repo: 'https://github.com/mbaran0v/python-sample-app.git'
        dest: /home/user
        update: yes  # Does a git pull if the repo already exists
    
    - pip:
        requirements: /home/user/requirements.txt  
        executable: pip3.6
        
    - name: Create systemd service 
      copy:
        src: .service
        dest: /etc/systemd/system/TestApp.service
        
    - name: start systemd app service
        systemd: name=TestApp.service state=restarted enabled=yes
        
    - name: Run application:
      shell: export FLASK_APP=app.py
             export POSTGRESQL_URL=postgresql://test_user:DMg00LhU@127.0.0.1/app
             flask db upgrade
      args:
         chdir: /home/test
