---
- name: Install Python-APP
  gather_facts: No
  hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgcheck: no

    - name: Install Python repo
      yum:
        name:
          - centos-release-scl
        state: present

    - name: Install PostgreSQL repo
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present

    - name: Install Nginx
      yum:
        name:
          - nginx
        state: present

    - name: Install PostgreSQL
      yum:
        name:
          - postgresql11
          - postgresql-contrib
          - postgresql11-server
        state: present

    - name: Init database
      command: /usr/pgsql-11/bin/postgresql-11-setup initdb

    - service:
        name: postgresql-11
        state: started

    - name: Install Python 3.6
      yum:
        name:
          - python36
          - python36-devel
          - python36-pip
          - gcc
          - postgresql-devel
          - python-pip
          - python-devel
        state: present

    - name: clone repo
      git:
        repo: 'https://github.com/mbaran0v/python-sample-app.git'
        dest: /home/user/1
        update: yes  # Does a git pull if the repo already exists

    - pip:
        requirements: /home/user/1/requirements.txt
        executable: pip3.6

    - pip:
        name: psycopg2
        executable: pip

    - name: Create test database
      postgresql_db:
        name: test

    - name: Create a PostrgeSQL database user
      postgresql_user:
        db: test
        name: test_user
        password: DMg00LhU
        priv: "ALL/products:ALL"
        expires: infinity

    - name: Create systemd service
      copy:
        src: .service
        dest: /etc/systemd/system/TestApp.service

    - name: Run application
      shell: export FLASK_APP=app.py
             export POSTGRESQL_URL=postgresql://test_user:DMg00LhU@127.0.0.1/app
             flask db upgrade
      args:
         chdir: /home/test
