---
- name: Install Nginx
  gather_facts: No
  hosts: 127.0.0.1
  connection: local

  tasks:
  
  - name: Add Epel repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgcheck: no

   - name: Install Nginx
      yum:
        name:
          - nginx
        state: present

    - name: Copy Nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx
        follow: yes     
    
    - service:
        name: nginx
        state: started
        enabled: yes 
