---
- name: Install Python-APP
  gather_facts: No
  hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Install Python 3.6
      yum:
        name:
          - python36
          - python36-devel
          - python36-pip
          - gcc
          - postgresql-devel
          - python-pip
          - python-devel
        state: present

    - name: clone repo
      git:
        repo: 'https://github.com/mbaran0v/python-sample-app.git'
        dest: /home/user/1
        update: yes  # Does a git pull if the repo already exists

    - pip:
        requirements: /home/user/1/requirements.txt
        executable: pip3.6
    
    - pip:
        name: gunicorn
        executable: pip3.6

    - pip:
        name: psycopg2
        executable: pip

    - name: Create test database
      become: true
      become_user: postgres
      postgresql_db:
        name: test

    - name: Create a PostrgeSQL database user
      become: true
      become_user: postgres 
      postgresql_user:
        db: test
        name: test_user
        password: md59547825b576517549329fbe5eeb199fb
        encrypted: 'yes'
        expires: infinity
        
    - name: Run application
      shell: export FLASK_APP=app.py
             export POSTGRESQL_URL=postgresql://test_user:DMg00LhU@127.0.0.1/app
             flask db upgrade
      args:
        chdir: /home/user/1

    - name: Create systemd service
      copy:
        src: .service
        dest: /etc/systemd/system/TestApp.service
    
    - service:
        name: TestApp.service
        state: started
        enabled: yes 
