- name: Install Gunicorn
  pip:
    name: gunicorn
    executable: pip3.6
    
- name: Run application
  shell: export FLASK_APP=app.py
    export POSTGRESQL_URL=postgresql://test_user:DMg00LhU@127.0.0.1/app
    flask db upgrade
  args:
  chdir: /home/test_user/app

- name: Create systemd service
  copy:
    src: ./templates/TestApp
    dest: /etc/systemd/system/TestApp.service

- name: Create python-app as service
  service:
    name: TestApp.service
    state: started
    enabled: yes 
