---
- name: Configure PostgreSQL server
  hosts: localhost
  become: true
  roles:
    - { role: ANXS.postgresql }
  vars_files:
    - ../environments/postgresql.yml

- name: Configure nginx server
  hosts: localhost
  become: true
  roles:
    - { role: nginx }
  vars_files:
    - ../environments/nginx.yml
    
- name: Configure PostgreSQL server
  hosts: localhost
  become: true
  roles:
    - { role: python-app } 
